# Lag-Based Trading Strategy Configuration
# This file configures the lag-based trading strategy for meme coins and DeFi tokens

# Data Configuration
data_path: "data/historical/processed"
timeframe: "5min"
analysis_days: 30

# Asset Configuration
leader_assets:
  - "BTC"    # Bitcoin - primary leader
  - "ETH"    # Ethereum - secondary leader  
  - "SOL"    # Solana - tertiary leader

follower_assets:
  - "WIF"      # dogwifhat
  - "FARTCOIN" # Fartcoin
  - "POPCAT"   # Popcat
  - "BOME"     # Book of Meme
  - "PEPE"     # Pepe
  - "BOME"     # Book of Meme
  - "SHIB"     # Shiba Inu
  - "FLOKI"    # Floki

# Signal Parameters
threshold: 1.5              # Minimum leader move percentage to trigger signal
max_lag_minutes: 60         # Maximum lag time to consider for follower response
min_correlation: 0.3        # Minimum correlation coefficient between leader and follower
volume_confirmation: true   # Whether to require volume confirmation
min_volume_ratio: 1.2       # Minimum volume increase for confirmation

# Risk Management
risk_per_trade: 0.02        # 2% risk per trade
max_positions: 3            # Maximum concurrent positions
stop_loss_pct: 0.05         # 5% stop loss
take_profit_pct: 0.10       # 10% take profit

# Analysis Parameters
correlation_window: "1H"    # Rolling correlation window
move_calculation_window: "5min"  # Window for move calculation
volume_window: "15min"      # Window for volume analysis

# Output Configuration
output_dir: "results/lag_strategy"

# Trading Integration
enable_live_trading: false  # Whether to enable live trading
exchange: "bitget"          # Default exchange for trading
demo_mode: true             # Whether to use demo account

# Performance Tracking
track_performance: true     # Whether to track performance metrics
save_trades: true          # Whether to save individual trades
generate_reports: true     # Whether to generate analysis reports

# Advanced Parameters
# These parameters can be tuned based on analysis results

# Threshold optimization
thresholds_to_test: [0.5, 1.0, 1.5, 2.0, 3.0, 5.0]

# Correlation analysis
correlation_windows: ["1H", "4H", "1D", "7D"]

# Move analysis
move_timeframes: [5, 15, 30, 60]  # minutes

# Volume analysis
volume_analysis_enabled: true
volume_smoothing_window: 20  # periods for volume smoothing

# Signal filtering
min_signal_confidence: 0.3   # Minimum confidence for signal generation
max_signals_per_day: 10      # Maximum signals per day per asset pair

# Backtesting
backtest_initial_capital: 10000
backtest_commission: 0.001   # 0.1% commission
backtest_slippage: 0.0005    # 0.05% slippage

# Real-time parameters
real_time_update_interval: 30  # seconds
signal_expiry_minutes: 15      # minutes after which signal expires

# Notifications
enable_notifications: false
notification_methods:
  - "console"
  - "log_file"
  # - "email"  # Uncomment to enable email notifications
  # - "telegram"  # Uncomment to enable Telegram notifications

# Logging
log_level: "INFO"
log_file: "logs/lag_strategy.log"
log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Data validation
validate_data_quality: true
min_data_points: 1000        # Minimum data points required for analysis
max_missing_data_pct: 0.1    # Maximum percentage of missing data allowed

# Strategy variants
# You can define different strategy variants for different market conditions

strategy_variants:
  conservative:
    threshold: 2.0
    min_correlation: 0.5
    risk_per_trade: 0.01
    max_positions: 2
    
  aggressive:
    threshold: 1.0
    min_correlation: 0.2
    risk_per_trade: 0.03
    max_positions: 5
    
  balanced:
    threshold: 1.5
    min_correlation: 0.3
    risk_per_trade: 0.02
    max_positions: 3

# Market regime detection
market_regime_detection:
  enabled: true
  volatility_window: "24H"
  high_volatility_threshold: 0.05  # 5% daily volatility
  low_volatility_threshold: 0.02   # 2% daily volatility

# Performance benchmarks
performance_benchmarks:
  min_win_rate: 0.4          # 40% minimum win rate
  min_profit_factor: 1.2     # 1.2 minimum profit factor
  max_drawdown: 0.15         # 15% maximum drawdown
  min_sharpe_ratio: 0.5      # 0.5 minimum Sharpe ratio 

# Mode selection
# Set to true to use grouped_followers mapping, false to use all followers for all leaders
# If grouped_mode is true but grouped_followers is not set, will default to all-followers mode
# If grouped_mode is false, follower_assets will be used for all leaders
# Example usage shown below

grouped_mode: false

grouped_followers:
  BTC:
    - "FARTCOIN"
    - "SPX"
    - "WIF"
    - "PEPE"
    - "SHIB"
    - "BRETT"
    - "BGB"
    - "FLOKI"
    - "TRUMP"
    - "POPCAT"
    - "PENGU"
    - "DODGE"
    - "GRASS"
    - "FWOG"
    - "AI16z"
    - "GIGA"
    - "GOAT"
    - "CHILLGUY"
    - "DRIFT"
    - "JUP"
    - "UNI"
    - "CAKE"
    - "ORCA"
    - "BIGTIME"
    - "FET"
    - "AAVE"
    - "AVAX"
    - "LINK"
    - "SUI"
    - "ADA"
    - "IMX"
    - "BNB"
  ETH:
    - "BRETT"
    - "AI16z"
    - "MEW"
    - "MOODENG"
    - "BOME"
    - "PEPECOIN"
    - "PI"
    - "PNUT"
    - "PONKE"
    - "SPX"
    - "SHIB"
    - "FLOKI"
    - "FWOG"
    - "GRASS"
    - "GOAT"
    - "GIGA"
    - "IMX"
    - "LINK"
    - "AVAX"
    - "AAVE"
    - "ADA"
    - "BNB"
  SOL:
    - "WIF"
    - "POPCAT"
    - "PENGU"
    - "FARTCOIN"
    - "TRUMP"
    - "BOME"
    - "FWOG"
    - "GOAT"
    - "CHILLGUY"
    - "DRIFT"
    - "JUP"
    - "UNI"
    - "CAKE"
    - "ORCA"
    - "BIGTIME"
    - "FET"
    - "AAVE"
    - "AVAX"
    - "LINK"
    - "SUI"
    - "ADA"
    - "IMX"
    - "BNB" 