[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
init-if-needed = true

[programs.localnet]
quantdesk_perp_dex = "GcpEyGMJg9AvEx8LgAyzyUNTPWFxovHxtmQ4vVWuWu3a"

[programs.devnet]
quantdesk_perp_dex = "GcpEyGMJg9AvEx8LgAyzyUNTPWFxovHxtmQ4vVWuWu3a"

[programs.testnet]
quantdesk_perp_dex = "GcpEyGMJg9AvEx8LgAyzyUNTPWFxovHxtmQ4vVWuWu3a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/keys/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
