[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
quantdesk_perp_dex = "G7isTpCkw8TWhPhozSuZMbUjTEF8Jf8xxAguZyL39L8J"

[programs.devnet]
quantdesk_perp_dex = "G7isTpCkw8TWhPhozSuZMbUjTEF8Jf8xxAguZyL39L8J"

[programs.testnet]
quantdesk_perp_dex = "G7isTpCkw8TWhPhozSuZMbUjTEF8Jf8xxAguZyL39L8J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
