name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd backend
        npm ci
    
    - name: Run linting
      run: |
        cd backend
        npm run lint
    
    - name: Run tests
      run: |
        cd backend
        npm test
      env:
        NODE_ENV: test
    
    - name: Build
      run: |
        cd backend
        npm run build

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run linting
      run: |
        cd frontend
        npm run lint
    
    - name: Run tests
      run: |
        cd frontend
        npm test
    
    - name: Build
      run: |
        cd frontend
        npm run build

  test-smart-contracts:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Setup Solana
      uses: coral-xyz/setup-anchor@v0.1.0
      with:
        anchor-version: "0.31.0"
    
    - name: Install dependencies
      run: |
        cd contracts/smart-contracts
        npm ci
    
    - name: Check formatting
      run: |
        cd contracts/smart-contracts
        cargo fmt --all -- --check
    
    - name: Run clippy
      run: |
        cd contracts/smart-contracts
        cargo clippy --all-targets --all-features -- -D warnings
    
    - name: Build contracts
      run: |
        cd contracts/smart-contracts
        anchor build
    
    - name: Run tests
      run: |
        cd contracts/smart-contracts
        anchor test --skip-local-validator

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Audit backend dependencies
      run: |
        cd backend
        npm audit --audit-level=moderate
    
    - name: Audit frontend dependencies
      run: |
        cd frontend
        npm audit --audit-level=moderate
    
    - name: Audit smart contract dependencies
      run: |
        cd contracts/smart-contracts
        npm audit --audit-level=moderate

  build-and-deploy:
    needs: [test-backend, test-frontend, test-smart-contracts, security-audit]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Build all projects
      run: |
        cd backend && npm ci && npm run build
        cd ../frontend && npm ci && npm run build
        cd ../contracts/smart-contracts && npm ci && anchor build
    
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # Add deployment commands here
    
    - name: Run integration tests
      run: |
        echo "Running integration tests..."
        # Add integration test commands here
